title: Clearing the stage in Scratch
description: Clear the stage of Pen lines and stamps
theme: orange # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 # possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: "art"
technologies: "scratch"
site_areas:
steps:
  - title: Clearing the stage in Scratch
